def add_one(x: int) -> int:
    return x + 2  # This is an error!
